# Configuración simplificada para Pure-FTPd con MySQL en DDEV
MYSQLServer     db
MYSQLPort       3306
MYSQLUser       db
MYSQLPassword   db
MYSQLDatabase   utrecar_ftp_db

MYSQLCrypt      md5
MYSQLGetPW      SELECT password FROM ftp_users WHERE user="\L"
MYSQLGetUID     SELECT uid FROM ftp_users WHERE user="\L"
MYSQLGetGID     SELECT gid FROM ftp_users WHERE user="\L"
MYSQLGetDir     SELECT dir FROM ftp_users WHERE user="\L"
