services:
  web:
    networks:
      ddev_default:
        ipv4_address: 172.18.0.101
  db:
    networks:
      ddev_default:
        ipv4_address: 172.18.0.102
  phpmyadmin:
    networks:
      ddev_default:
        ipv4_address: 172.18.0.103

networks:
  ddev_default:
    external: true
    name: ddev-admin-platform_default
